[package]
name = "book_order"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
reqwest = { version = "*",  features = ["json"] }
tokio = { version = "*", features = ["full"] }
eyre = "*"
serde_json = "*"
tokio-tungstenite = { version = "*", features = ["native-tls"]}
futures-util = {version = "*", default-features = false, features = ["sink", "std"] }